### ISSUE TITLE
Comments on Git Book; Suggestion for RStudio GUI Step-by-Step Book or Training Class

### ISSUE THREAD

**Issue by krocana** [ADFG-DSF/Git_book#7]
I think the Git Book is really solid and helpful as it is. There are spelling and grammatical errors throughout the book, and perhaps places that could be clearer, use less lingo, or explain the use of terms for the reader. However, I feel like it is a helpful guide for those who have had some exposure to Git in the past, really want to learn how Git works, and learn the specific Git code to do tasks. So, awesome job!!

Based on my personal journey trying to understand Git, I would point new hires with no Git experience towards a Git, GitHub, and GUI training class, teach them about Git myself, or point them towards a separate book detailing a more step-by-step version of how to set up a GitHub account, how to set up Git, how to set up R and RStudio, and then instructions about how to use Git, GitHub, and RStudio together. Personally, I really struggled to understand Git and the whole conversation about this Git Book until I used those instructions from the standards group to set up Git and then was shown in-person how to use Git and connect to GitHub through RStudio. I understand this Git Book more every day, and think it is a useful tool should I ever need to dig deeper into Git code to do tasks. So far, the functionality of RStudio and GitHub have been enough for the analyses I do. It is also a fairly gradual learning curve to learn how to use Git through RStudio for RStudio users, compared to learning the ins and outs of Git.

Thus, why I'm suggesting we create a Git, GitHub, & RStudio step-by-step book or training class.

**Comment by adamreimer** [comment]
Have you thought about adding an appendix with installation instructions? I agree Git installation will hold some people back. I'm imagining the reader of this book to be folks who would hopefully not need installation instructions for R or RStudio. 

I guess I need more information about what you mean by "how to use Git". I thought that was done in detail in the introduction chapter. If you meant how to use Git through RStudio maybe you could help me expand the appendix on RStudio.

**Comment by krocana** [comment]
No, I haven't thought about adding an appendix with instructions to install Git. But yes, I think Git installation instructions would be a helpful addition for the Git Book. However, I don't believe I am the person to add Git installation instructions. I didn't have to install Git because it was already on my computer. I also trial and errored my way through setting up Git until it worked.

I mean using Git through RStudio. I'm suggesting a new book instead of adding to the current Git book because I think it'd be helpful if the instructions were written in a different perspective. The Git Book is currently written in the mindset of a Git user (e.g., someone who is familiar and comfortable with Git code and using Git by itself). My suggestion is about writing instructions for an RStudio user to use Git and GitHub. For example, open RStudio and Git. The book then has explicit instructions for how to do the following: Connect Git and RStudio. Create a repository in GitHub. Create a local repository by creating an R project in RStudio and connecting it to the repository in GitHub using HTTPS or SSH keys. Then stepped through what the buttons in the Git tab of RStudio can now do by being shown the buttons in RStudio and what happens when those buttons are pressed.

**Comment by adamreimer** [comment]
Thanks for the comments. I'll close this issue since your suggestions are for a separate project. I don't agree that it has to be a separate project since using Git through RStudio (or any GUI) is just using Git indirectly. In fact, I had hoped to flesh out the use of GUIs (and the RStudio Gui specifically) as appendices to this book through collaboration with Git users who preferred to interact with Git indirectly. That said, I encourage you to create the instructions you think are appropriate as they will likely be useful to someone else.

In the meantime, please start migrating your projects into the ADF&G Git account using the guidance found in appendix B.

**Comment by adamreimer** [comment]
Oops, meant to close w comment.
